<a href="https://colab.research.google.com/github/DasherXx/machine-learning-bootcamp/blob/main/Kopia_notatnika_template.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [101]:
import numpy as np
import pandas as pd
import sklearn

sklearn.__version__

'1.6.1'

In [102]:
data = {
    'size' : ['XL', 'L', 'M', 'L', 'M'],
    'color' : ['red', 'green', 'blue', 'green', 'red'],
    'gender' : ['female', 'male', 'male', 'female', 'female'],
    'price' : [199.0, 89.0, 99.0, 129.0, 79.0],
    'weight' : [500, 450, 300, 380, 410],
    'bought' : ['yes', 'no', 'yes', 'no', 'yes']
}

df_raw = pd.DataFrame(data=data)
df_raw

  size  color  gender  price  weight bought
0   XL    red  female  199.0     500    yes
1    L  green    male   89.0     450     no
2    M   blue    male   99.0     300    yes
3    L  green  female  129.0     380     no
4    M    red  female   79.0     410    yes

In [103]:
df = df_raw.copy()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   size    5 non-null      object
 1   color   5 non-null      object
 2   gender  5 non-null      object
 3   price   5 non-null      float64
 4   weight  5 non-null      int64
 5   bought  5 non-null      object
dtypes: float64(1), int64(1), object(4)
memory usage: 372.0+ bytes

In [104]:
for col in ['size', 'color', 'gender', 'bought']:
  df[col] = df[col].astype('category')

df['weight'] = df['weight'].astype('float')

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   size    5 non-null      category
 1   color   5 non-null      category
 2   gender  5 non-null      category
 3   price   5 non-null      float64
 4   weight  5 non-null      float64
 5   bought  5 non-null      category
dtypes: category(4), float64(2)
memory usage: 744.0 bytes

In [105]:
df.describe()

            price      weight
count    5.000000    5.000000
mean   119.000000  408.000000
std     48.476799   75.299402
min     79.000000  300.000000
25%     89.000000  380.000000
50%     99.000000  410.000000
75%    129.000000  450.000000
max    199.000000  500.000000

In [106]:
df.describe().T

        count   mean        std    min    25%    50%    75%    max
price     5.0  119.0  48.476799   79.0   89.0   99.0  129.0  199.0
weight    5.0  408.0  75.299402  300.0  380.0  410.0  450.0  500.0

In [107]:
df.describe(include=['category']).T

       count unique     top freq
size       5      3       L    2
color      5      3   green    2
gender     5      2  female    3
bought     5      2     yes    3

In [108]:
df

  size  color  gender  price  weight bought
0   XL    red  female  199.0   500.0    yes
1    L  green    male   89.0   450.0     no
2    M   blue    male   99.0   300.0    yes
3    L  green  female  129.0   380.0     no
4    M    red  female   79.0   410.0    yes

In [109]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
le.fit(df['bought'])
le.transform(df['bought'])

array([1, 0, 1, 0, 1])

In [110]:
le.fit_transform(df['bought'])

array([1, 0, 1, 0, 1])

In [111]:
le.classes_

array(['no', 'yes'], dtype=object)

In [112]:
df['bought'] = le.fit_transform(df['bought'])
df

  size  color  gender  price  weight  bought
0   XL    red  female  199.0   500.0       1
1    L  green    male   89.0   450.0       0
2    M   blue    male   99.0   300.0       1
3    L  green  female  129.0   380.0       0
4    M    red  female   79.0   410.0       1

In [113]:
le.inverse_transform(df['bought'])

array(['yes', 'no', 'yes', 'no', 'yes'], dtype=object)

In [114]:
df['bought'] = le.inverse_transform(df['bought'])
df

  size  color  gender  price  weight bought
0   XL    red  female  199.0   500.0    yes
1    L  green    male   89.0   450.0     no
2    M   blue    male   99.0   300.0    yes
3    L  green  female  129.0   380.0     no
4    M    red  female   79.0   410.0    yes

In [115]:
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder(sparse_output=False)
encoder.fit(df[['size']])

OneHotEncoder(sparse_output=False)

In [116]:
encoder.transform(df[['size']])

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [117]:
encoder.categories_

[array(['L', 'M', 'XL'], dtype=object)]

In [118]:
encoder = OneHotEncoder(drop='first', sparse_output=False)
encoder.fit(df[['size']])
encoder.transform(df[['size']])

array([[0., 1.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [1., 0.]])

In [119]:
df

  size  color  gender  price  weight bought
0   XL    red  female  199.0   500.0    yes
1    L  green    male   89.0   450.0     no
2    M   blue    male   99.0   300.0    yes
3    L  green  female  129.0   380.0     no
4    M    red  female   79.0   410.0    yes

In [123]:
pd.get_dummies(data=df)

,price,weight,size_L,size_M,size_XL,color_blue,color_green,color_red,gender_female,gender_male,bought_no,bought_yes
0,199.0,500.0,False,False,True,False,False,True,True,False,False,True
1,89.0,450.0,True,False,False,False,True,False,False,True,True,False
2,99.0,300.0,False,True,False,True,False,False,False,True,False,True
3,129.0,380.0,True,False,False,False,True,False,True,False,True,False
4,79.0,410.0,False,True,False,False,False,True,True,False,False,True

In [124]:
pd.get_dummies(data=df, drop_first=True)

,price,weight,size_M,size_XL,color_green,color_red,gender_male,bought_yes
0,199.0,500.0,False,True,False,True,False,True
1,89.0,450.0,False,False,True,False,True,False
2,99.0,300.0,True,False,False,False,True,True
3,129.0,380.0,False,False,True,False,False,False
4,79.0,410.0,True,False,False,True,False,True

In [125]:
pd.get_dummies(data=df, drop_first=True, prefix='new')

   price  weight  new_M  new_XL  new_green  new_red  new_male  new_yes
0  199.0   500.0  False    True      False     True     False     True
1   89.0   450.0  False   False       True    False      True    False
2   99.0   300.0   True   False      False    False      True     True
3  129.0   380.0  False   False       True    False     False    False
4   79.0   410.0   True   False      False     True     False     True

In [126]:
pd.get_dummies(data=df, drop_first=True, prefix_sep='-')

,price,weight,size-M,size-XL,color-green,color-red,gender-male,bought-yes
0,199.0,500.0,False,True,False,True,False,True
1,89.0,450.0,False,False,True,False,True,False
2,99.0,300.0,True,False,False,False,True,True
3,129.0,380.0,False,False,True,False,False,False
4,79.0,410.0,True,False,False,True,False,True

In [127]:
pd.get_dummies(data=df, drop_first=True, columns=['size'])

   color  gender  price  weight bought  size_M  size_XL
0    red  female  199.0   500.0    yes   False     True
1  green    male   89.0   450.0     no   False    False
2   blue    male   99.0   300.0    yes    True    False
3  green  female  129.0   380.0     no   False    False
4    red  female   79.0   410.0    yes    True    False

In [128]:
print(f"{df['price']}\n")
print(f"Średnia: {df['price'].mean()}")
print(f"Odchylenie standardowe: {df['price'].std():.4f}")

0    199.0
1     89.0
2     99.0
3    129.0
4     79.0
Name: price, dtype: float64

Średnia: 119.0
Odchylenie standardowe: 48.4768

In [129]:
(df['price'] - df['price'].mean()) / df['price'].std()

0    1.650274
1   -0.618853
2   -0.412568
3    0.206284
4   -0.825137
Name: price, dtype: float64